%General Mission Analysis Tool(GMAT) Script
%Created: 2019-11-20 17:15:43


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft Terra;
GMAT Terra.DateFormat = UTCGregorian;
GMAT Terra.Epoch = '10 Nov 2019 00:00:00.000';
GMAT Terra.EphemerisName = '../TLE/Terra_Nov-09-2019.txt';
GMAT Terra.Id = 'TERRA';


%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator TLEProp;
GMAT TLEProp.Type = TLE;
GMAT TLEProp.StepSize = 300;

%TLEProp.J2 = -4.84165374886470e-04   %"J2",                // J2   J2 value
%TLEProp.J3 =    %"J3",                // J3   J3 value
%TLEProp.J4 =    %"J4",                // J4   J4 value
%TLEProp.KE = 0.07436686   %"KE",                // KE   sqrt(mu) in earth-radii**1.5/MIN
%TLEProp.QO =    %"QO",                // QO   Upper bound of atmospheric model in KM
%TLEProp.SO =    %"SO",                // SO   Lower bound of atmospheric model in KM
%TLEProp.ER = 6378.1363   %"ER",                // ER   Earth equatorial radius in KM.
%TLEProp.AE = 1.0   %"AE"                 // AE   Distance units/earth radius111

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create ReportFile rf;
rf.Filename = TerraPropagation.txt
rf.Add = {Terra.UTCGregorian, Terra.X, Terra.Y, Terra.Z, Terra.VX, Terra.VY, Terra.VZ}


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;

Propagate TLEProp(Terra) {Terra.ElapsedDays = 1.0};
